export { default as StartScreen } from './HomeScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Dashboard } from './Dashboard'
export { default as NewsScreen } from './NewsScreen'
export { default as Horoscope } from './Horoscope'
export { default as Weather} from './Weather'
export { default as LastScreen } from './LastScreen'